repository_type: pipeline
lint:
  files_unchanged:
    - assets/multiqc_config.yml
    - assets/nf-core-sarek_logo_light.png
    - docs/images/nf-core-sarek_logo_dark.png
    - docs/images/nf-core-sarek_logo_light.png
    - lib/NfcoreTemplate.groovy
